/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Libreria;

import javax.swing.JOptionPane;

/**
 *
 * @author Master
 */
public class pagoFrame extends javax.swing.JFrame {

    public static pagoFrame instancia;
    private String monto = null;
    /**
     * Creates new form pagoFrame
     */
    
    
    public pagoFrame(String monto) {
        initComponents();
        instancia = this;
        this.monto = monto;
        this.lmonto.setText(lmonto.getText()+" "+monto);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lcambio = new javax.swing.JLabel();
        lmonto = new javax.swing.JLabel();
        lpago = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pago Service");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/libreria central.png"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lcambio.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        lcambio.setText("Su cambio: $");
        jPanel1.add(lcambio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        lmonto.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        lmonto.setText("Monto: $");
        jPanel1.add(lmonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        lpago.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        lpago.setText("Pago: $");
        jPanel1.add(lpago, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 50, -1, -1));

        jButton1.setText("Cerrar");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public boolean change()
    {
       boolean ok = false;
       double entrada = Double.parseDouble(JOptionPane.showInputDialog(null, "Efectivo de compra","Java",1));
       if(!(entrada < Double.parseDouble(monto)))
       {
       
       this.lpago.setText(lpago.getText()+ " "+Double.toString(entrada));
       this.lcambio.setText(lcambio.getText()+" "+String.format("%.2f",(entrada-Double.parseDouble(monto)))); 
       ok = true;
       }
       else
       {
       this.lpago.setText(lpago.getText() + " Error");
       this.lcambio.setText(lcambio.getText() + " Error"); 
       }
       return ok;
       
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lcambio;
    private javax.swing.JLabel lmonto;
    private javax.swing.JLabel lpago;
    // End of variables declaration//GEN-END:variables
}
